-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    id serial NOT NULL,
    dni character varying NOT NULL,
    password character varying NOT NULL,
    "firstName" character varying NOT NULL,
    "lastName" character varying NOT NULL,
    email character varying,
    "phoneNumber" character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Accounts"
(
    id serial NOT NULL,
    "userId" integer NOT NULL,
    "accountNumber" character varying NOT NULL,
    balance numeric NOT NULL DEFAULT 0.00,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    id serial NOT NULL,
    "senderAccountId" integer NOT NULL,
    "receiverAccountId" integer NOT NULL,
    amount numeric NOT NULL,
    type character varying,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Accounts"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transactions"
    ADD FOREIGN KEY ("senderAccountId", "receiverAccountId")
    REFERENCES public."Accounts" (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;